version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8099:8080"
    volumes:
      # - "$PWD/jenkins_home:/var/jenkins_home"
      - "C:\\Users\\alexl\\Desktop\\Jenkins-Udemy\\jenkins_data\\jenkins_home:/var/jenkins_home"

    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    networks:
      - net
networks:
  net:
